### ISSUE TITLE
Not parsing storyline json files without place.name="Home"

### ISSUE THREAD

**Issue by dotkrnl** [claygregory/moves-on-deck#1]
Thank you a lot for this great app for people to parse Moves json data!

When processing my Moves storyline.json, an error `Oops, the file you provided doesn't look like a Moves storyline` would be shown.

After investigation, I found it occurred in function `locateHome` in app/js/util.js which is attempting to find a location with `place.name==='Home'`.

I would suggest having a fallback location when `Home` absent. Or warns non-developers to add a location with name="Home".

Thank you again! This app is awesome!

**Comment by claygregory** [comment]
Hi @dotkrnl 

Thanks so much for tracking this down! I just pushed a fix —

If home isn't defined, I decided to fallback to the most visited location, which may be a good guess for home. Since `home` is only used to center map initially, and to report "farthest from home" in the info panel, there's little harm guessing it incorrectly (and certainly better than failing entirely)

Thanks again, and glad you've enjoyed using the app.
